name: Build

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: cp .env.example .env
      - run: pnpm exec prisma db push
      - run: pnpm run build
